name: manim

on:
  push:
    paths:
      - '.github/workflows/manim.yml'
      - 'pkginstall.sh'
      - 'manim/**'
      # Dependencies
      - 'python-cloup/**'
      - 'python-glcontext/**'
      - 'python-isosurfaces/**'
      - 'python-manimpango/**'
      - 'python-moderngl-git/**'
      - 'python-moderngl-window/**'
      - 'python-mapbox-earcut/**'
      - 'python-pyrr/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install manim
        working-directory: manim
        run: |
          ../pkginstall.sh user=groctel pkg=manim

      - name: Test manim
        run: |
          manim render --help
          curl -L https://raw.githubusercontent.com/ManimCommunity/manim/master/example_scenes/basic.py -o basic.py
          manim basic.py SquareToCircle
