name: python-moderngl-window

on:
  push:
    paths:
      - '.github/workflows/python-moderngl-window.yml'
      - 'pkginstall.sh'
      - 'python-moderngl-window/**'
      # Dependencies
      - 'python-moderngl-git/**'
      - 'python-pyrr/**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install python-moderngl-window
        working-directory: python-moderngl-window
        run: |
          ../pkginstall.sh user=groctel pkg=python-moderngl-window
